export default {
  nav: { browse: "تصفح", library: "مكتبة", messages: "رسائل", upload: "رفع", profile: "الملف الشخصي", signIn: "تسجيل الدخول", getStarted: "ابدأ", logOut: "تسجيل الخروج" },
  browse: { title: "اكتشف الكتب", subtitle: "استكشف آلاف الكتب التي يشاركها مجتمعنا", searchPlaceholder: "ابحث عن العناوين والمؤلفين والأوصاف...", allGenres: "جميع الأنواع", noResults: "لم يتم العثور على كتب", noResultsHint: "جرب بحثاً أو نوعاً مختلفاً", downloads: "تنزيلات", comments: "تعليقات", people: "أشخاص", books: "كتب", searchPeople: "ابحث عن القراء والمؤلفين...", noPeople: "لم يتم العثور على مستخدمين" },
  book: { readOnline: "اقرأ أونلاين", download: "تنزيل", saveToLibrary: "حفظ في المكتبة", removeFromLibrary: "إزالة من المكتبة", by: "بقلم", uploadedOn: "رُفع في", comments: "نقاش", noComments: "لا تعليقات بعد. كن أول من يشارك رأيه!", addComment: "إضافة تعليق...", postComment: "نشر تعليق", deleteComment: "حذف", private: "خاص" },
  upload: { title: "رفع كتاب", editTitle: "تعديل الكتاب", bookTitle: "عنوان الكتاب", titlePlaceholder: "أدخل عنوان الكتاب", description: "الوصف", descriptionPlaceholder: "عم يتحدث هذا الكتاب؟", genre: "النوع", selectGenre: "اختر نوعاً", coverImage: "صورة الغلاف", bookFile: "ملف الكتاب", bookFilePlaceholder: "ارفع PDF أو EPUB", visibility: "الظهور", public: "عام", private: "خاص", publicDesc: "يمكن لأي شخص اكتشاف هذا الكتاب وتنزيله", privateDesc: "أنت فقط يمكنك رؤية هذا الكتاب", submit: "رفع الكتاب", saveChanges: "حفظ التغييرات", uploading: "جارٍ الرفع...", saving: "جارٍ الحفظ...", uploadSuccess: "تم رفع الكتاب بنجاح!", updateSuccess: "تم تحديث الكتاب بنجاح!", changeCover: "تغيير الغلاف", changeFile: "تغيير الملف", currentFile: "الملف الحالي" },
  profile: { myProfile: "ملفي الشخصي", managePresence: "أدر حضورك العام", editProfile: "تعديل الملف", saveChanges: "حفظ التغييرات", cancel: "إلغاء", saving: "جارٍ الحفظ...", displayName: "الاسم المعروض", username: "اسم المستخدم", bio: "نبذة", bioPlaceholder: "أخبر المجتمع قليلاً عنك...", joinedDate: "انضم في", books: "كتب", book: "كتاب", myBooks: "كتبي", uploadNew: "رفع جديد", noBooks: "لم ترفع أي كتب بعد.", uploadFirst: "ارفع كتابك الأول", noBio: "لا نبذة بعد. تعرف على المجتمع.", changeBanner: "تغيير صورة البانر", changeAvatar: "تغيير الصورة الرمزية", publicBooks: "كتب", noBooksPublic: "لا كتب عامة بعد.", dmButton: "رسالة" },
  library: { title: "مكتبتي", subtitle: "كتبك المحفوظة", empty: "مكتبتك فارغة", emptyHint: "تصفح الكتب واحفظ ما تريد قراءته", browseCta: "تصفح الكتب", savedOn: "حُفظ في" },
  messages: { title: "الرسائل", noConversations: "لا محادثات بعد", noConversationsHint: "ابدأ محادثة من ملف مستخدم", typeMessage: "اكتب رسالة...", send: "إرسال", you: "أنت" },
  common: { loading: "جارٍ التحميل...", error: "حدث خطأ ما", retry: "حاول مجدداً", back: "رجوع" },
  auth: { welcomeBack: "مرحباً بعودتك إلى Lumina", joinCommunity: "انضم إلى مجتمع Lumina", signInDesc: "سجّل دخولك للوصول إلى مكتبتك ومتابعة القراءة", signUpDesc: "شارك الكتب وابنِ مكتبتك وتواصل مع القراء" },
  language: { label: "اللغة", en: "English", es: "Español", de: "Deutsch", ru: "Русский", fr: "Français", pt: "Português", it: "Italiano", ja: "日本語", ko: "한국어", "zh-CN": "中文(简体)", "zh-TW": "中文(繁體)", ar: "العربية", hi: "हिन्दी", tr: "Türkçe", pl: "Polski", nl: "Nederlands", sv: "Svenska" },
  feed: { title: "تغذيتي", subtitle: "منتقى لأذواقك", trending: "الأكثر رواجاً", basedOn: "لأنك تحب", noPreferences: "حدد أنواعك المفضلة للحصول على توصيات مخصصة", setPreferences: "تعيين التفضيلات" },
  quiz: { title: "ماذا تحب أن تقرأ؟", subtitle: "اختر أنواعك المفضلة وسنخصص تجربتك", confirm: "لنبدأ!", skip: "تخطي الآن" },
};
