export default {
  nav: { browse: "ब्राउज़", library: "पुस्तकालय", messages: "संदेश", upload: "अपलोड", profile: "प्रोफ़ाइल", signIn: "साइन इन", getStarted: "शुरू करें", logOut: "लॉग आउट" },
  browse: { title: "किताबें खोजें", subtitle: "हमारे समुदाय द्वारा साझा की गई हजारों किताबें एक्सप्लोर करें", searchPlaceholder: "शीर्षक, लेखक, विवरण खोजें...", allGenres: "सभी शैलियाँ", noResults: "कोई किताब नहीं मिली", noResultsHint: "कोई अलग खोज या शैली आज़माएं", downloads: "डाउनलोड", comments: "टिप्पणियाँ", people: "लोग", books: "किताबें", searchPeople: "पाठकों और लेखकों को खोजें...", noPeople: "कोई उपयोगकर्ता नहीं मिला" },
  book: { readOnline: "ऑनलाइन पढ़ें", download: "डाउनलोड", saveToLibrary: "पुस्तकालय में सहेजें", removeFromLibrary: "पुस्तकालय से हटाएं", by: "द्वारा", uploadedOn: "अपलोड किया", comments: "चर्चा", noComments: "अभी तक कोई टिप्पणी नहीं। अपने विचार पहले साझा करें!", addComment: "टिप्पणी जोड़ें...", postComment: "टिप्पणी पोस्ट करें", deleteComment: "हटाएं", private: "निजी" },
  upload: { title: "किताब अपलोड करें", editTitle: "किताब संपादित करें", bookTitle: "किताब का शीर्षक", titlePlaceholder: "किताब का शीर्षक दर्ज करें", description: "विवरण", descriptionPlaceholder: "यह किताब किस बारे में है?", genre: "शैली", selectGenre: "एक शैली चुनें", coverImage: "कवर छवि", bookFile: "किताब फ़ाइल", bookFilePlaceholder: "PDF या EPUB अपलोड करें", visibility: "दृश्यता", public: "सार्वजनिक", private: "निजी", publicDesc: "कोई भी इस किताब को खोज और डाउनलोड कर सकता है", privateDesc: "केवल आप इस किताब को देख सकते हैं", submit: "किताब अपलोड करें", saveChanges: "परिवर्तन सहेजें", uploading: "अपलोड हो रहा है...", saving: "सहेजा जा रहा है...", uploadSuccess: "किताब सफलतापूर्वक अपलोड हुई!", updateSuccess: "किताब सफलतापूर्वक अपडेट हुई!", changeCover: "कवर बदलें", changeFile: "फ़ाइल बदलें", currentFile: "वर्तमान फ़ाइल" },
  profile: { myProfile: "मेरी प्रोफ़ाइल", managePresence: "अपनी सार्वजनिक उपस्थिति प्रबंधित करें", editProfile: "प्रोफ़ाइल संपादित करें", saveChanges: "परिवर्तन सहेजें", cancel: "रद्द करें", saving: "सहेजा जा रहा है...", displayName: "प्रदर्शन नाम", username: "उपयोगकर्ता नाम", bio: "जीवनी", bioPlaceholder: "समुदाय को अपने बारे में बताएं...", joinedDate: "जुड़ा", books: "किताबें", book: "किताब", myBooks: "मेरी किताबें", uploadNew: "नई अपलोड करें", noBooks: "आपने अभी तक कोई किताब अपलोड नहीं की।", uploadFirst: "अपनी पहली किताब अपलोड करें", noBio: "अभी कोई जीवनी नहीं। समुदाय को अपने बारे में बताएं।", changeBanner: "बैनर बदलें", changeAvatar: "अवतार बदलें", publicBooks: "की किताबें", noBooksPublic: "अभी कोई सार्वजनिक किताब नहीं।", dmButton: "संदेश" },
  library: { title: "मेरा पुस्तकालय", subtitle: "आपकी सहेजी हुई किताबें", empty: "आपका पुस्तकालय खाली है", emptyHint: "किताबें ब्राउज़ करें और जो पढ़ना चाहते हैं उन्हें सहेजें", browseCta: "किताबें ब्राउज़ करें", savedOn: "सहेजा" },
  messages: { title: "संदेश", noConversations: "अभी कोई बातचीत नहीं", noConversationsHint: "किसी उपयोगकर्ता की प्रोफ़ाइल से बातचीत शुरू करें", typeMessage: "संदेश टाइप करें...", send: "भेजें", you: "आप" },
  common: { loading: "लोड हो रहा है...", error: "कुछ गलत हो गया", retry: "पुनः प्रयास करें", back: "वापस" },
  auth: { welcomeBack: "Lumina पर वापस स्वागत है", joinCommunity: "Lumina समुदाय में शामिल हों", signInDesc: "अपनी लाइब्रेरी तक पहुंचने के लिए साइन इन करें", signUpDesc: "किताबें साझा करें, लाइब्रेरी बनाएं, पाठकों से जुड़ें" },
  language: { label: "भाषा", en: "English", es: "Español", de: "Deutsch", ru: "Русский", fr: "Français", pt: "Português", it: "Italiano", ja: "日本語", ko: "한국어", "zh-CN": "中文(简体)", "zh-TW": "中文(繁體)", ar: "العربية", hi: "हिन्दी", tr: "Türkçe", pl: "Polski", nl: "Nederlands", sv: "Svenska" },
  feed: { title: "आपका फ़ीड", subtitle: "आपके स्वाद के अनुसार क्यूरेटेड", trending: "ट्रेंडिंग", basedOn: "क्योंकि आपको पसंद है", noPreferences: "व्यक्तिगत अनुशंसाओं के लिए अपनी पसंदीदा शैलियाँ सेट करें", setPreferences: "प्राथमिकताएं सेट करें" },
  quiz: { title: "आप क्या पढ़ना पसंद करते हैं?", subtitle: "अपनी पसंदीदा शैलियाँ चुनें और हम आपका अनुभव व्यक्तिगत बनाएंगे", confirm: "चलिए शुरू करें!", skip: "अभी छोड़ें" },
};
