export default {
  nav: { browse: "Sfoglia", library: "Biblioteca", messages: "Messaggi", upload: "Carica", profile: "Profilo", signIn: "Accedi", getStarted: "Inizia", logOut: "Disconnetti" },
  browse: { title: "Scopri libri", subtitle: "Esplora migliaia di libri condivisi dalla nostra comunità", searchPlaceholder: "Cerca titoli, autori, descrizioni...", allGenres: "Tutti i generi", noResults: "Nessun libro trovato", noResultsHint: "Prova una ricerca o genere diverso", downloads: "download", comments: "commenti", people: "Persone", books: "Libri", searchPeople: "Cerca lettori e autori...", noPeople: "Nessun utente trovato" },
  book: { readOnline: "Leggi online", download: "Scarica", saveToLibrary: "Salva in biblioteca", removeFromLibrary: "Rimuovi dalla biblioteca", by: "di", uploadedOn: "Caricato il", comments: "Discussione", noComments: "Ancora nessun commento. Sii il primo a condividere la tua opinione!", addComment: "Aggiungi un commento...", postComment: "Pubblica commento", deleteComment: "Elimina", private: "Privato" },
  upload: { title: "Carica un libro", editTitle: "Modifica libro", bookTitle: "Titolo del libro", titlePlaceholder: "Inserisci il titolo del libro", description: "Descrizione", descriptionPlaceholder: "Di cosa parla questo libro?", genre: "Genere", selectGenre: "Seleziona un genere", coverImage: "Immagine di copertina", bookFile: "File del libro", bookFilePlaceholder: "Carica PDF o EPUB", visibility: "Visibilità", public: "Pubblico", private: "Privato", publicDesc: "Chiunque può scoprire e scaricare questo libro", privateDesc: "Solo tu puoi vedere questo libro", submit: "Carica libro", saveChanges: "Salva modifiche", uploading: "Caricamento...", saving: "Salvataggio...", uploadSuccess: "Libro caricato con successo!", updateSuccess: "Libro aggiornato con successo!", changeCover: "Cambia copertina", changeFile: "Cambia file", currentFile: "File attuale" },
  profile: { myProfile: "Il mio profilo", managePresence: "Gestisci la tua presenza pubblica", editProfile: "Modifica profilo", saveChanges: "Salva modifiche", cancel: "Annulla", saving: "Salvataggio...", displayName: "Nome visualizzato", username: "Nome utente", bio: "Bio", bioPlaceholder: "Racconta alla comunità un po' di te...", joinedDate: "Iscritto", books: "libri", book: "libro", myBooks: "I miei libri", uploadNew: "Carica nuovo", noBooks: "Non hai ancora caricato libri.", uploadFirst: "Carica il tuo primo libro", noBio: "Ancora nessuna bio. Raccontati alla comunità.", changeBanner: "Cambia banner", changeAvatar: "Cambia avatar", publicBooks: "Libri di", noBooksPublic: "Ancora nessun libro pubblico.", dmButton: "Messaggio" },
  library: { title: "La mia biblioteca", subtitle: "I tuoi libri salvati", empty: "La tua biblioteca è vuota", emptyHint: "Sfoglia i libri e salva quelli che vuoi leggere", browseCta: "Sfoglia libri", savedOn: "Salvato il" },
  messages: { title: "Messaggi", noConversations: "Ancora nessuna conversazione", noConversationsHint: "Inizia una conversazione dal profilo di un utente", typeMessage: "Scrivi un messaggio...", send: "Invia", you: "Tu" },
  common: { loading: "Caricamento...", error: "Qualcosa è andato storto", retry: "Riprova", back: "Indietro" },
  auth: { welcomeBack: "Bentornato su Lumina", joinCommunity: "Unisciti alla comunità Lumina", signInDesc: "Accedi per entrare nella tua biblioteca e continuare a leggere", signUpDesc: "Condividi libri, costruisci la tua biblioteca e connettiti con i lettori" },
  language: { label: "Lingua", en: "English", es: "Español", de: "Deutsch", ru: "Русский", fr: "Français", pt: "Português", it: "Italiano", ja: "日本語", ko: "한국어", "zh-CN": "中文(简体)", "zh-TW": "中文(繁體)", ar: "العربية", hi: "हिन्दी", tr: "Türkçe", pl: "Polski", nl: "Nederlands", sv: "Svenska" },
  feed: { title: "Il tuo feed", subtitle: "Curato per i tuoi gusti", trending: "Di tendenza", basedOn: "Perché ti piace", noPreferences: "Imposta i tuoi generi preferiti per ottenere raccomandazioni personalizzate", setPreferences: "Imposta preferenze" },
  quiz: { title: "Cosa ami leggere?", subtitle: "Scegli i tuoi generi preferiti e personalizzeremo la tua esperienza", confirm: "Andiamo!", skip: "Salta per ora" },
};
