export default {
  nav: { browse: "ブラウズ", library: "ライブラリ", messages: "メッセージ", upload: "アップロード", profile: "プロフィール", signIn: "ログイン", getStarted: "始める", logOut: "ログアウト" },
  browse: { title: "本を発見", subtitle: "コミュニティが共有する何千もの本を探索しましょう", searchPlaceholder: "タイトル、著者、説明を検索...", allGenres: "すべてのジャンル", noResults: "本が見つかりません", noResultsHint: "別の検索またはジャンルをお試しください", downloads: "ダウンロード", comments: "コメント", people: "ユーザー", books: "本", searchPeople: "読者と著者を検索...", noPeople: "ユーザーが見つかりません" },
  book: { readOnline: "オンラインで読む", download: "ダウンロード", saveToLibrary: "ライブラリに保存", removeFromLibrary: "ライブラリから削除", by: "著者：", uploadedOn: "アップロード日", comments: "ディスカッション", noComments: "まだコメントはありません。最初に感想を共有しましょう！", addComment: "コメントを追加...", postComment: "コメントを投稿", deleteComment: "削除", private: "非公開" },
  upload: { title: "本をアップロード", editTitle: "本を編集", bookTitle: "本のタイトル", titlePlaceholder: "本のタイトルを入力", description: "説明", descriptionPlaceholder: "この本はどんな内容ですか？", genre: "ジャンル", selectGenre: "ジャンルを選択", coverImage: "カバー画像", bookFile: "本のファイル", bookFilePlaceholder: "PDFまたはEPUBをアップロード", visibility: "公開設定", public: "公開", private: "非公開", publicDesc: "誰でもこの本を発見・ダウンロードできます", privateDesc: "あなただけがこの本を見られます", submit: "本をアップロード", saveChanges: "変更を保存", uploading: "アップロード中...", saving: "保存中...", uploadSuccess: "本が正常にアップロードされました！", updateSuccess: "本が正常に更新されました！", changeCover: "カバーを変更", changeFile: "ファイルを変更", currentFile: "現在のファイル" },
  profile: { myProfile: "マイプロフィール", managePresence: "公開プレゼンスを管理", editProfile: "プロフィールを編集", saveChanges: "変更を保存", cancel: "キャンセル", saving: "保存中...", displayName: "表示名", username: "ユーザー名", bio: "自己紹介", bioPlaceholder: "コミュニティに自己紹介を...", joinedDate: "参加日", books: "冊", book: "冊", myBooks: "マイブック", uploadNew: "新しくアップロード", noBooks: "まだ本をアップロードしていません。", uploadFirst: "最初の本をアップロード", noBio: "まだ自己紹介がありません。コミュニティに紹介しましょう。", changeBanner: "バナーを変更", changeAvatar: "アバターを変更", publicBooks: "の本", noBooksPublic: "まだ公開されている本はありません。", dmButton: "メッセージ" },
  library: { title: "マイライブラリ", subtitle: "保存した本", empty: "ライブラリが空です", emptyHint: "本を探して読みたい本を保存しましょう", browseCta: "本を探す", savedOn: "保存日" },
  messages: { title: "メッセージ", noConversations: "まだ会話はありません", noConversationsHint: "ユーザープロフィールから会話を始めましょう", typeMessage: "メッセージを入力...", send: "送信", you: "あなた" },
  common: { loading: "読み込み中...", error: "エラーが発生しました", retry: "再試行", back: "戻る" },
  auth: { welcomeBack: "Luminaへようこそ", joinCommunity: "Luminaコミュニティに参加", signInDesc: "ライブラリにアクセスして読書を続けましょう", signUpDesc: "本を共有し、ライブラリを作り、読者とつながりましょう" },
  language: { label: "言語", en: "English", es: "Español", de: "Deutsch", ru: "Русский", fr: "Français", pt: "Português", it: "Italiano", ja: "日本語", ko: "한국어", "zh-CN": "中文(简体)", "zh-TW": "中文(繁體)", ar: "العربية", hi: "हिन्दी", tr: "Türkçe", pl: "Polski", nl: "Nederlands", sv: "Svenska" },
  feed: { title: "あなたのフィード", subtitle: "あなたの好みにあわせてキュレーション", trending: "トレンド", basedOn: "お気に入りだから", noPreferences: "好きなジャンルを設定してパーソナライズされたおすすめを取得", setPreferences: "設定する" },
  quiz: { title: "何を読むのが好きですか？", subtitle: "好きなジャンルを選んでカスタマイズしましょう", confirm: "はじめる！", skip: "今はスキップ" },
};
