export default {
  nav: { browse: "탐색", library: "라이브러리", messages: "메시지", upload: "업로드", profile: "프로필", signIn: "로그인", getStarted: "시작하기", logOut: "로그아웃" },
  browse: { title: "책 발견", subtitle: "커뮤니티가 공유하는 수천 권의 책을 탐색하세요", searchPlaceholder: "제목, 저자, 설명 검색...", allGenres: "모든 장르", noResults: "책을 찾을 수 없습니다", noResultsHint: "다른 검색어나 장르를 시도해보세요", downloads: "다운로드", comments: "댓글", people: "사람", books: "책", searchPeople: "독자와 저자 검색...", noPeople: "사용자를 찾을 수 없습니다" },
  book: { readOnline: "온라인으로 읽기", download: "다운로드", saveToLibrary: "라이브러리에 저장", removeFromLibrary: "라이브러리에서 제거", by: "저자:", uploadedOn: "업로드됨", comments: "토론", noComments: "아직 댓글이 없습니다. 첫 번째로 의견을 공유해보세요!", addComment: "댓글 추가...", postComment: "댓글 게시", deleteComment: "삭제", private: "비공개" },
  upload: { title: "책 업로드", editTitle: "책 편집", bookTitle: "책 제목", titlePlaceholder: "책 제목 입력", description: "설명", descriptionPlaceholder: "이 책은 어떤 내용인가요?", genre: "장르", selectGenre: "장르 선택", coverImage: "표지 이미지", bookFile: "책 파일", bookFilePlaceholder: "PDF 또는 EPUB 업로드", visibility: "공개 설정", public: "공개", private: "비공개", publicDesc: "누구나 이 책을 발견하고 다운로드할 수 있습니다", privateDesc: "당신만 이 책을 볼 수 있습니다", submit: "책 업로드", saveChanges: "변경 사항 저장", uploading: "업로드 중...", saving: "저장 중...", uploadSuccess: "책이 성공적으로 업로드되었습니다!", updateSuccess: "책이 성공적으로 업데이트되었습니다!", changeCover: "표지 변경", changeFile: "파일 변경", currentFile: "현재 파일" },
  profile: { myProfile: "내 프로필", managePresence: "공개 프레즌스 관리", editProfile: "프로필 편집", saveChanges: "변경 사항 저장", cancel: "취소", saving: "저장 중...", displayName: "표시 이름", username: "사용자 이름", bio: "소개", bioPlaceholder: "커뮤니티에 자신을 소개해보세요...", joinedDate: "가입일", books: "권", book: "권", myBooks: "내 책", uploadNew: "새로 업로드", noBooks: "아직 업로드한 책이 없습니다.", uploadFirst: "첫 번째 책 업로드", noBio: "아직 소개가 없습니다. 커뮤니티에 자신을 소개해보세요.", changeBanner: "배너 변경", changeAvatar: "아바타 변경", publicBooks: "의 책", noBooksPublic: "아직 공개 책이 없습니다.", dmButton: "메시지" },
  library: { title: "내 라이브러리", subtitle: "저장한 책", empty: "라이브러리가 비어 있습니다", emptyHint: "책을 탐색하고 읽고 싶은 책을 저장하세요", browseCta: "책 탐색", savedOn: "저장됨" },
  messages: { title: "메시지", noConversations: "아직 대화가 없습니다", noConversationsHint: "사용자 프로필에서 대화를 시작하세요", typeMessage: "메시지 입력...", send: "보내기", you: "나" },
  common: { loading: "로딩 중...", error: "문제가 발생했습니다", retry: "다시 시도", back: "뒤로" },
  auth: { welcomeBack: "Lumina에 다시 오신 것을 환영합니다", joinCommunity: "Lumina 커뮤니티에 참여하세요", signInDesc: "로그인하여 라이브러리에 접근하고 계속 읽으세요", signUpDesc: "책을 공유하고, 라이브러리를 만들고, 독자들과 연결하세요" },
  language: { label: "언어", en: "English", es: "Español", de: "Deutsch", ru: "Русский", fr: "Français", pt: "Português", it: "Italiano", ja: "日本語", ko: "한국어", "zh-CN": "中文(简体)", "zh-TW": "中文(繁體)", ar: "العربية", hi: "हिन्दी", tr: "Türkçe", pl: "Polski", nl: "Nederlands", sv: "Svenska" },
  feed: { title: "내 피드", subtitle: "취향에 맞게 큐레이션됨", trending: "인기 급상승", basedOn: "좋아하기 때문에", noPreferences: "좋아하는 장르를 설정하여 맞춤 추천을 받으세요", setPreferences: "환경설정" },
  quiz: { title: "무엇을 읽는 것을 좋아하나요?", subtitle: "좋아하는 장르를 선택하면 경험을 맞춤화해드립니다", confirm: "시작하기!", skip: "나중에" },
};
