export default {
  nav: { browse: "Bladeren", library: "Bibliotheek", messages: "Berichten", upload: "Uploaden", profile: "Profiel", signIn: "Inloggen", getStarted: "Beginnen", logOut: "Uitloggen" },
  browse: { title: "Boeken Ontdekken", subtitle: "Verken duizenden boeken gedeeld door onze gemeenschap", searchPlaceholder: "Zoek titels, auteurs, beschrijvingen...", allGenres: "Alle genres", noResults: "Geen boeken gevonden", noResultsHint: "Probeer een andere zoekterm of genre", downloads: "downloads", comments: "reacties", people: "Mensen", books: "Boeken", searchPeople: "Zoek lezers en auteurs...", noPeople: "Geen gebruikers gevonden" },
  book: { readOnline: "Online lezen", download: "Downloaden", saveToLibrary: "Opslaan in bibliotheek", removeFromLibrary: "Verwijderen uit bibliotheek", by: "door", uploadedOn: "Geüpload", comments: "Discussie", noComments: "Nog geen reacties. Wees de eerste!", addComment: "Reactie toevoegen...", postComment: "Reactie plaatsen", deleteComment: "Verwijderen", private: "Privé" },
  upload: { title: "Boek uploaden", editTitle: "Boek bewerken", bookTitle: "Boektitel", titlePlaceholder: "Voer boektitel in", description: "Beschrijving", descriptionPlaceholder: "Waar gaat dit boek over?", genre: "Genre", selectGenre: "Selecteer een genre", coverImage: "Omslagafbeelding", bookFile: "Boekbestand", bookFilePlaceholder: "PDF of EPUB uploaden", visibility: "Zichtbaarheid", public: "Openbaar", private: "Privé", publicDesc: "Iedereen kan dit boek ontdekken en downloaden", privateDesc: "Alleen jij kunt dit boek zien", submit: "Boek uploaden", saveChanges: "Wijzigingen opslaan", uploading: "Uploaden...", saving: "Opslaan...", uploadSuccess: "Boek succesvol geüpload!", updateSuccess: "Boek succesvol bijgewerkt!", changeCover: "Omslag wijzigen", changeFile: "Bestand wijzigen", currentFile: "Huidig bestand" },
  profile: { myProfile: "Mijn profiel", managePresence: "Beheer je openbare aanwezigheid", editProfile: "Profiel bewerken", saveChanges: "Wijzigingen opslaan", cancel: "Annuleren", saving: "Opslaan...", displayName: "Weergavenaam", username: "Gebruikersnaam", bio: "Bio", bioPlaceholder: "Vertel de gemeenschap iets over jezelf...", joinedDate: "Lid sinds", books: "boeken", book: "boek", myBooks: "Mijn boeken", uploadNew: "Nieuw uploaden", noBooks: "Je hebt nog geen boeken geüpload.", uploadFirst: "Upload je eerste boek", noBio: "Nog geen bio. Vertel de gemeenschap over jezelf.", changeBanner: "Banner wijzigen", changeAvatar: "Avatar wijzigen", publicBooks: "Boeken van", noBooksPublic: "Nog geen openbare boeken.", dmButton: "Bericht" },
  library: { title: "Mijn bibliotheek", subtitle: "Je opgeslagen boeken", empty: "Je bibliotheek is leeg", emptyHint: "Blader door boeken en sla op wat je wilt lezen", browseCta: "Door boeken bladeren", savedOn: "Opgeslagen" },
  messages: { title: "Berichten", noConversations: "Nog geen gesprekken", noConversationsHint: "Start een gesprek vanuit het profiel van een gebruiker", typeMessage: "Bericht typen...", send: "Verzenden", you: "Jij" },
  common: { loading: "Laden...", error: "Er ging iets mis", retry: "Opnieuw proberen", back: "Terug" },
  auth: { welcomeBack: "Welkom terug bij Lumina", joinCommunity: "Word lid van de Lumina-gemeenschap", signInDesc: "Log in voor toegang tot je bibliotheek", signUpDesc: "Deel boeken, bouw een bibliotheek en verbind met lezers" },
  language: { label: "Taal", en: "English", es: "Español", de: "Deutsch", ru: "Русский", fr: "Français", pt: "Português", it: "Italiano", ja: "日本語", ko: "한국어", "zh-CN": "中文(简体)", "zh-TW": "中文(繁體)", ar: "العربية", hi: "हिन्दी", tr: "Türkçe", pl: "Polski", nl: "Nederlands", sv: "Svenska" },
  feed: { title: "Jouw feed", subtitle: "Samengesteld voor jouw smaak", trending: "Trending", basedOn: "Omdat je houdt van", noPreferences: "Stel je favoriete genres in voor gepersonaliseerde aanbevelingen", setPreferences: "Voorkeuren instellen" },
  quiz: { title: "Wat lees je graag?", subtitle: "Kies je favoriete genres en we personaliseren je ervaring", confirm: "Laten we gaan!", skip: "Nu overslaan" },
};
