export default {
  nav: { browse: "Przeglądaj", library: "Biblioteka", messages: "Wiadomości", upload: "Prześlij", profile: "Profil", signIn: "Zaloguj", getStarted: "Zacznij", logOut: "Wyloguj" },
  browse: { title: "Odkryj Książki", subtitle: "Eksploruj tysiące książek udostępnianych przez naszą społeczność", searchPlaceholder: "Szukaj tytułów, autorów, opisów...", allGenres: "Wszystkie gatunki", noResults: "Nie znaleziono książek", noResultsHint: "Spróbuj innego wyszukiwania lub gatunku", downloads: "pobrań", comments: "komentarzy", people: "Osoby", books: "Książki", searchPeople: "Szukaj czytelników i autorów...", noPeople: "Nie znaleziono użytkowników" },
  book: { readOnline: "Czytaj online", download: "Pobierz", saveToLibrary: "Zapisz do biblioteki", removeFromLibrary: "Usuń z biblioteki", by: "autor:", uploadedOn: "Przesłano", comments: "Dyskusja", noComments: "Brak komentarzy. Bądź pierwszy!", addComment: "Dodaj komentarz...", postComment: "Opublikuj komentarz", deleteComment: "Usuń", private: "Prywatne" },
  upload: { title: "Prześlij książkę", editTitle: "Edytuj książkę", bookTitle: "Tytuł książki", titlePlaceholder: "Wprowadź tytuł książki", description: "Opis", descriptionPlaceholder: "O czym jest ta książka?", genre: "Gatunek", selectGenre: "Wybierz gatunek", coverImage: "Okładka", bookFile: "Plik książki", bookFilePlaceholder: "Prześlij PDF lub EPUB", visibility: "Widoczność", public: "Publiczne", private: "Prywatne", publicDesc: "Każdy może odkryć i pobrać tę książkę", privateDesc: "Tylko ty możesz zobaczyć tę książkę", submit: "Prześlij książkę", saveChanges: "Zapisz zmiany", uploading: "Przesyłanie...", saving: "Zapisywanie...", uploadSuccess: "Książka przesłana pomyślnie!", updateSuccess: "Książka zaktualizowana pomyślnie!", changeCover: "Zmień okładkę", changeFile: "Zmień plik", currentFile: "Bieżący plik" },
  profile: { myProfile: "Mój profil", managePresence: "Zarządzaj swoją publiczną obecnością", editProfile: "Edytuj profil", saveChanges: "Zapisz zmiany", cancel: "Anuluj", saving: "Zapisywanie...", displayName: "Wyświetlana nazwa", username: "Nazwa użytkownika", bio: "Bio", bioPlaceholder: "Powiedz społeczności coś o sobie...", joinedDate: "Dołączył", books: "książek", book: "książka", myBooks: "Moje książki", uploadNew: "Prześlij nową", noBooks: "Nie przesłałeś jeszcze żadnych książek.", uploadFirst: "Prześlij swoją pierwszą książkę", noBio: "Brak bio. Opowiedz społeczności o sobie.", changeBanner: "Zmień baner", changeAvatar: "Zmień avatar", publicBooks: "Książki", noBooksPublic: "Brak publicznych książek.", dmButton: "Wiadomość" },
  library: { title: "Moja biblioteka", subtitle: "Twoje zapisane książki", empty: "Twoja biblioteka jest pusta", emptyHint: "Przeglądaj książki i zapisuj te, które chcesz przeczytać", browseCta: "Przeglądaj książki", savedOn: "Zapisano" },
  messages: { title: "Wiadomości", noConversations: "Brak rozmów", noConversationsHint: "Rozpocznij rozmowę z profilu użytkownika", typeMessage: "Napisz wiadomość...", send: "Wyślij", you: "Ty" },
  common: { loading: "Ładowanie...", error: "Coś poszło nie tak", retry: "Spróbuj ponownie", back: "Wstecz" },
  auth: { welcomeBack: "Witaj ponownie w Lumina", joinCommunity: "Dołącz do społeczności Lumina", signInDesc: "Zaloguj się, aby uzyskać dostęp do biblioteki", signUpDesc: "Udostępniaj książki, buduj bibliotekę i łącz się z czytelnikami" },
  language: { label: "Język", en: "English", es: "Español", de: "Deutsch", ru: "Русский", fr: "Français", pt: "Português", it: "Italiano", ja: "日本語", ko: "한국어", "zh-CN": "中文(简体)", "zh-TW": "中文(繁體)", ar: "العربية", hi: "हिन्दी", tr: "Türkçe", pl: "Polski", nl: "Nederlands", sv: "Svenska" },
  feed: { title: "Twój kanał", subtitle: "Dopasowane do Twoich upodobań", trending: "Na czasie", basedOn: "Bo lubisz", noPreferences: "Ustaw ulubione gatunki, aby otrzymać spersonalizowane rekomendacje", setPreferences: "Ustaw preferencje" },
  quiz: { title: "Co lubisz czytać?", subtitle: "Wybierz ulubione gatunki, a spersonalizujemy Twoje doświadczenie", confirm: "Zaczynajmy!", skip: "Pomiń na razie" },
};
