export default {
  nav: { browse: "Bläddra", library: "Bibliotek", messages: "Meddelanden", upload: "Ladda upp", profile: "Profil", signIn: "Logga in", getStarted: "Kom igång", logOut: "Logga ut" },
  browse: { title: "Upptäck böcker", subtitle: "Utforska tusentals böcker delade av vår gemenskap", searchPlaceholder: "Sök titlar, författare, beskrivningar...", allGenres: "Alla genrer", noResults: "Inga böcker hittades", noResultsHint: "Prova en annan sökning eller genre", downloads: "nedladdningar", comments: "kommentarer", people: "Personer", books: "Böcker", searchPeople: "Sök läsare och författare...", noPeople: "Inga användare hittades" },
  book: { readOnline: "Läs online", download: "Ladda ner", saveToLibrary: "Spara i bibliotek", removeFromLibrary: "Ta bort från bibliotek", by: "av", uploadedOn: "Uppladdad", comments: "Diskussion", noComments: "Inga kommentarer ännu. Var den första!", addComment: "Lägg till kommentar...", postComment: "Posta kommentar", deleteComment: "Radera", private: "Privat" },
  upload: { title: "Ladda upp en bok", editTitle: "Redigera bok", bookTitle: "Boktitel", titlePlaceholder: "Ange boktitel", description: "Beskrivning", descriptionPlaceholder: "Vad handlar den här boken om?", genre: "Genre", selectGenre: "Välj en genre", coverImage: "Omslagsbild", bookFile: "Bokfil", bookFilePlaceholder: "Ladda upp PDF eller EPUB", visibility: "Synlighet", public: "Offentlig", private: "Privat", publicDesc: "Vem som helst kan hitta och ladda ner den här boken", privateDesc: "Bara du kan se den här boken", submit: "Ladda upp bok", saveChanges: "Spara ändringar", uploading: "Laddar upp...", saving: "Sparar...", uploadSuccess: "Bok uppladdad!", updateSuccess: "Bok uppdaterad!", changeCover: "Byt omslag", changeFile: "Byt fil", currentFile: "Nuvarande fil" },
  profile: { myProfile: "Min profil", managePresence: "Hantera din offentliga närvaro", editProfile: "Redigera profil", saveChanges: "Spara ändringar", cancel: "Avbryt", saving: "Sparar...", displayName: "Visningsnamn", username: "Användarnamn", bio: "Bio", bioPlaceholder: "Berätta lite om dig själv...", joinedDate: "Gick med", books: "böcker", book: "bok", myBooks: "Mina böcker", uploadNew: "Ladda upp ny", noBooks: "Du har inte laddat upp några böcker ännu.", uploadFirst: "Ladda upp din första bok", noBio: "Ingen bio ännu. Berätta om dig själv.", changeBanner: "Byt banner", changeAvatar: "Byt avatar", publicBooks: "Böcker av", noBooksPublic: "Inga offentliga böcker ännu.", dmButton: "Meddelande" },
  library: { title: "Mitt bibliotek", subtitle: "Dina sparade böcker", empty: "Ditt bibliotek är tomt", emptyHint: "Bläddra bland böcker och spara dem du vill läsa", browseCta: "Bläddra bland böcker", savedOn: "Sparad" },
  messages: { title: "Meddelanden", noConversations: "Inga konversationer ännu", noConversationsHint: "Starta en konversation från en användares profil", typeMessage: "Skriv ett meddelande...", send: "Skicka", you: "Du" },
  common: { loading: "Laddar...", error: "Något gick fel", retry: "Försök igen", back: "Tillbaka" },
  auth: { welcomeBack: "Välkommen tillbaka till Lumina", joinCommunity: "Gå med i Lumina-gemenskapen", signInDesc: "Logga in för att komma åt ditt bibliotek", signUpDesc: "Dela böcker, bygg ett bibliotek och anslut med läsare" },
  language: { label: "Språk", en: "English", es: "Español", de: "Deutsch", ru: "Русский", fr: "Français", pt: "Português", it: "Italiano", ja: "日本語", ko: "한국어", "zh-CN": "中文(简体)", "zh-TW": "中文(繁體)", ar: "العربية", hi: "हिन्दी", tr: "Türkçe", pl: "Polski", nl: "Nederlands", sv: "Svenska" },
  feed: { title: "Ditt flöde", subtitle: "Kuraterat efter dina smaker", trending: "Trending", basedOn: "Eftersom du gillar", noPreferences: "Ange dina favoritgenrer för personliga rekommendationer", setPreferences: "Ange inställningar" },
  quiz: { title: "Vad läser du gärna?", subtitle: "Välj dina favoritgenrer och vi anpassar din upplevelse", confirm: "Sätt igång!", skip: "Hoppa över nu" },
};
