export default {
  nav: { browse: "Keşfet", library: "Kütüphane", messages: "Mesajlar", upload: "Yükle", profile: "Profil", signIn: "Giriş yap", getStarted: "Başla", logOut: "Çıkış yap" },
  browse: { title: "Kitapları Keşfet", subtitle: "Topluluğumuzun paylaştığı binlerce kitabı keşfedin", searchPlaceholder: "Başlık, yazar, açıklama ara...", allGenres: "Tüm türler", noResults: "Kitap bulunamadı", noResultsHint: "Farklı bir arama veya tür deneyin", downloads: "indirme", comments: "yorum", people: "Kişiler", books: "Kitaplar", searchPeople: "Okuyucu ve yazar ara...", noPeople: "Kullanıcı bulunamadı" },
  book: { readOnline: "Çevrimiçi oku", download: "İndir", saveToLibrary: "Kütüphaneye kaydet", removeFromLibrary: "Kütüphaneden kaldır", by: "Yazar:", uploadedOn: "Yüklendi", comments: "Tartışma", noComments: "Henüz yorum yok. İlk yorumu siz yapın!", addComment: "Yorum ekle...", postComment: "Yorum gönder", deleteComment: "Sil", private: "Özel" },
  upload: { title: "Kitap yükle", editTitle: "Kitabı düzenle", bookTitle: "Kitap başlığı", titlePlaceholder: "Kitap başlığını girin", description: "Açıklama", descriptionPlaceholder: "Bu kitap ne hakkında?", genre: "Tür", selectGenre: "Bir tür seçin", coverImage: "Kapak resmi", bookFile: "Kitap dosyası", bookFilePlaceholder: "PDF veya EPUB yükle", visibility: "Görünürlük", public: "Herkese açık", private: "Özel", publicDesc: "Herkes bu kitabı keşfedip indirebilir", privateDesc: "Sadece siz bu kitabı görebilirsiniz", submit: "Kitabı yükle", saveChanges: "Değişiklikleri kaydet", uploading: "Yükleniyor...", saving: "Kaydediliyor...", uploadSuccess: "Kitap başarıyla yüklendi!", updateSuccess: "Kitap başarıyla güncellendi!", changeCover: "Kapağı değiştir", changeFile: "Dosyayı değiştir", currentFile: "Mevcut dosya" },
  profile: { myProfile: "Profilim", managePresence: "Genel varlığınızı yönetin", editProfile: "Profili düzenle", saveChanges: "Değişiklikleri kaydet", cancel: "İptal", saving: "Kaydediliyor...", displayName: "Görünen ad", username: "Kullanıcı adı", bio: "Biyografi", bioPlaceholder: "Topluluğa kendinizi tanıtın...", joinedDate: "Katıldı", books: "kitap", book: "kitap", myBooks: "Kitaplarım", uploadNew: "Yeni yükle", noBooks: "Henüz kitap yüklemediniz.", uploadFirst: "İlk kitabınızı yükleyin", noBio: "Henüz biyografi yok. Topluluğa kendinizi tanıtın.", changeBanner: "Banner'ı değiştir", changeAvatar: "Avatarı değiştir", publicBooks: "Kitapları", noBooksPublic: "Henüz genel kitap yok.", dmButton: "Mesaj" },
  library: { title: "Kütüphanem", subtitle: "Kaydedilen kitaplarınız", empty: "Kütüphaneniz boş", emptyHint: "Kitaplara göz atın ve okumak istediklerinizi kaydedin", browseCta: "Kitaplara göz at", savedOn: "Kaydedildi" },
  messages: { title: "Mesajlar", noConversations: "Henüz konuşma yok", noConversationsHint: "Bir kullanıcının profilinden konuşma başlatın", typeMessage: "Mesaj yazın...", send: "Gönder", you: "Siz" },
  common: { loading: "Yükleniyor...", error: "Bir şeyler ters gitti", retry: "Tekrar dene", back: "Geri" },
  auth: { welcomeBack: "Lumina'ya hoş geldiniz", joinCommunity: "Lumina topluluğuna katılın", signInDesc: "Kütüphanenize erişmek için giriş yapın", signUpDesc: "Kitap paylaşın, kütüphane oluşturun, okuyucularla bağlantı kurun" },
  language: { label: "Dil", en: "English", es: "Español", de: "Deutsch", ru: "Русский", fr: "Français", pt: "Português", it: "Italiano", ja: "日本語", ko: "한국어", "zh-CN": "中文(简体)", "zh-TW": "中文(繁體)", ar: "العربية", hi: "हिन्दी", tr: "Türkçe", pl: "Polski", nl: "Nederlands", sv: "Svenska" },
  feed: { title: "Beslemeniz", subtitle: "Zevklerinize göre düzenlendi", trending: "Trend", basedOn: "Sevdiğiniz için", noPreferences: "Kişiselleştirilmiş öneriler için favori türlerinizi ayarlayın", setPreferences: "Tercihleri ayarla" },
  quiz: { title: "Okumayı ne seversiniz?", subtitle: "Favori türlerinizi seçin ve deneyiminizi kişiselleştirelim", confirm: "Hadi gidelim!", skip: "Şimdilik geç" },
};
